DROP SEQUENCE UNIDADE_MEDIDA_SEQ;

DROP SEQUENCE CATEGORIA_SEQ;

DROP SEQUENCE AULA_SEQ;

DROP TABLE INGREDIENTE;

DROP TABLE UNIDADE_MEDIDA;

DROP TABLE AULA;

DROP TABLE CATEGORIA;


CREATE SEQUENCE UNIDADE_MEDIDA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE CATEGORIA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE AULA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE TABLE UNIDADE_MEDIDA
( 
    ID           INT          NOT NULL PRIMARY KEY,
    SIMBOLO      VARCHAR(3)   NOT NULL,
    DESCRICAO    VARCHAR(50)  NOT NULL
);
  
CREATE TABLE CATEGORIA
( 
    ID           INT          NOT NULL PRIMARY KEY,
    DESCRICAO    VARCHAR(50)  NOT NULL
);
  
CREATE TABLE AULA
( 
    ID           INT          NOT NULL PRIMARY KEY,
    DATA         DATE         NOT NULL,
    DESCRICAO    VARCHAR(50)  NOT NULL
);

CREATE TABLE INGREDIENTE
(
	ID                    INT	        NOT NULL PRIMARY KEY,
	NOME                  VARCHAR(100)  NOT NULL,
	QUANTIDADE_CALORICA   DECIMAL(6,2)  NOT NULL,
	APROVEITAMENTO        INT           NOT NULL,
	QUANTIDADE_ESTOQUE    DECIMAL(6,2)  NULL,
	CUSTO                 DECIMAL(18,2) NULL,
	ID_UNIDADE_MEDIDA     INT           NOT NULL,	
	CONSTRAINT INGREDIENTE_UNIDADE_FK 
	    FOREIGN KEY (ID_UNIDADE_MEDIDA) 
	    REFERENCES UNIDADE_MEDIDA(ID)
);

INSERT INTO UNIDADE_MEDIDA (ID, SIMBOLO, DESCRICAO) 
          VALUES (UNIDADE_MEDIDA_SEQ.NEXTVAL, 'KG', 'Kilograma');
INSERT INTO UNIDADE_MEDIDA (ID, SIMBOLO, DESCRICAO) 
          VALUES (UNIDADE_MEDIDA_SEQ.NEXTVAL, 'L', 'Litro');

SELECT * FROM UNIDADE_MEDIDA;

