DROP SEQUENCE AULA_SEQ;

DROP SEQUENCE CATEGORIA_SEQ;

DROP SEQUENCE PRODUTO_SEQ;

DROP SEQUENCE RECEITA_SEQ;

DROP SEQUENCE UNIDADE_MEDIDA_SEQ;

DROP TABLE AULA;

DROP TABLE PRODUTO;

DROP TABLE RECEITA;

DROP TABLE CATEGORIA;

DROP TABLE UNIDADE_MEDIDA;

CREATE SEQUENCE AULA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE CATEGORIA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE PRODUTO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE RECEITA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;  
 
CREATE SEQUENCE UNIDADE_MEDIDA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE AULA
( 
    ID           INT          NOT NULL PRIMARY KEY,
    DATA         DATE         NOT NULL,
    DESCRICAO    VARCHAR(50)  NOT NULL
);

CREATE TABLE CATEGORIA
( 
    ID           INT          NOT NULL PRIMARY KEY,
    DESCRICAO    VARCHAR(50)  NOT NULL
);

CREATE TABLE RECEITA
(
	ID					INT				NOT NULL PRIMARY KEY,
	NOME				VARCHAR(70)		NOT NULL,
	CLASSIFICAÇÃO		VARCHAR(50)		NULL,
	ID_CATEGORIA		INT				NOT NULL,
	CONSTRAINT RECEITA_CATEGORIA_FK
		FOREIGN KEY (ID_CATEGORIA)
		REFERENCES CATEGORIA(ID)
);
  
CREATE TABLE UNIDADE_MEDIDA
( 
    ID           INT          NOT NULL PRIMARY KEY,
    SIMBOLO      VARCHAR(3)   NOT NULL,
    DESCRICAO    VARCHAR(50)  NOT NULL
);

CREATE TABLE PRODUTO
(
	ID                    INT	        NOT NULL PRIMARY KEY,
	NOME                  VARCHAR(100)  NOT NULL,
	QUANTIDADE_CALORICA   DECIMAL(6,2)  NOT NULL,
	APROVEITAMENTO        INT           NOT NULL,
	QUANTIDADE_ESTOQUE    DECIMAL(6,2)  NULL,
	CUSTO                 DECIMAL(18,2) NULL,
	ID_UNIDADE_MEDIDA     INT           NOT NULL,	
	CONSTRAINT PRODUTO_UNIDADE_FK 
	    FOREIGN KEY (ID_UNIDADE_MEDIDA) 
	    REFERENCES UNIDADE_MEDIDA(ID)
);